# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('store_url', models.CharField(max_length=255, verbose_name='Store URL')),
                ('name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('syncing', 'Syncing')], default='disconnected', max_length=20, verbose_name='Status')),
                ('consumer_key', models.CharField(blank=True, max_length=255, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(blank=True, max_length=255, verbose_name='Consumer Secret')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret')),
                ('api_version', models.CharField(default='wc/v3', max_length=10, verbose_name='API Version')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Config')),
                ('sync_enabled', models.BooleanField(default=False, verbose_name='Sync Enabled')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('last_sync_status', models.CharField(blank=True, max_length=20, verbose_name='Last Sync Status')),
            ],
            options={
                'db_table': 'woocommerce_connect_connection',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WooCommerceSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('entity_type', models.CharField(choices=[('products', 'Products'), ('categories', 'Categories'), ('customers', 'Customers'), ('orders', 'Orders'), ('inventory', 'Inventory')], max_length=30, verbose_name='Entity Type')),
                ('action', models.CharField(max_length=20, verbose_name='Action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20, verbose_name='Status')),
                ('local_id', models.UUIDField(blank=True, null=True, verbose_name='Local ID')),
                ('remote_id', models.CharField(blank=True, max_length=100, verbose_name='Remote ID')),
                ('direction', models.CharField(blank=True, max_length=30, verbose_name='Direction')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='woocommerce_connect.woocommerceconnection', verbose_name='Connection')),
            ],
            options={
                'db_table': 'woocommerce_connect_synclog',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WooCommerceSyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('entity_type', models.CharField(choices=[('products', 'Products'), ('categories', 'Categories'), ('customers', 'Customers'), ('orders', 'Orders'), ('inventory', 'Inventory')], max_length=30, verbose_name='Entity Type')),
                ('action', models.CharField(max_length=20, verbose_name='Action')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('attempts', models.IntegerField(default=0, verbose_name='Attempts')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Max Attempts')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='woocommerce_connect.woocommerceconnection', verbose_name='Connection')),
            ],
            options={
                'db_table': 'woocommerce_connect_syncqueue',
                'ordering': ['-priority', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WooCommerceSyncMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('entity_type', models.CharField(choices=[('products', 'Products'), ('categories', 'Categories'), ('customers', 'Customers'), ('orders', 'Orders'), ('inventory', 'Inventory')], max_length=30, verbose_name='Entity Type')),
                ('local_id', models.UUIDField(verbose_name='Local ID')),
                ('remote_id', models.CharField(max_length=100, verbose_name='Remote ID')),
                ('remote_data_hash', models.CharField(blank=True, max_length=64, verbose_name='Remote Data Hash')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('sync_direction', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('to_woocommerce', 'To WooCommerce'), ('from_woocommerce', 'From WooCommerce')], default='bidirectional', max_length=30, verbose_name='Sync Direction')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='woocommerce_connect.woocommerceconnection', verbose_name='Connection')),
            ],
            options={
                'db_table': 'woocommerce_connect_syncmapping',
                'abstract': False,
                'unique_together': {('connection', 'entity_type', 'local_id'), ('connection', 'entity_type', 'remote_id')},
            },
        ),
    ]
